services:
  iuss-unife-watch:
    build: .
    container_name: iuss-unife-watch
    restart: unless-stopped
    environment:
      # Obbligatori: token e chat del tuo bot
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHAT_ID: ""

      # Opzionali/avanzati (solo se vuoi sovrascrivere i default dello script)
      # URL: "https://iuss.unife.it/it/iscriversi/bandi/bando-41"
      # CHECK_INTERVAL_SECONDS: "120"
      # KEEP_VERSIONS: "5"

      DATA_DIR: "/app/data"
    volumes:
      # Mappa i dati persistenti su Unraid
      - /mnt/user/appdata/iuss-unife-watch:/app/data
